title: Gayathri Magesh
description: Software Engineer | Backend, GenAI, Distributed Systems
theme: just-the-docs
author:
     name: Gayathri Magesh
     email: gayathrimagesh1291@gmail.com
url: "https://gayathrimagesh.github.io"
